<a href="https://colab.research.google.com/github/disha1409/MachineLearning/blob/master/BreastCanceripynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
import pandas as pd
import numpy as np
df=pd.read_excel('/content/drive/My Drive/dataset/BreastCancer_Prognostic_v1.xlsx')
df.head()
df.shape
df['Outcome']
#df.describe()
dfc=df.copy(deep=True)
dfc.shape

(198, 35)

In [124]:
dfc.head(30)

ID Outcome  ...  Tumor_Size  Lymph_Node_Status
0    119513       N  ...         5.0                  5
1      8423       N  ...         3.0                  2
2    842517       N  ...         2.5                  0
3    843483       N  ...         2.0                  0
4    843584       R  ...         3.5                  0
5    843786       R  ...         2.5                  0
6    844359       N  ...         1.5                  0
7    844582       R  ...         4.0                 10
8    844981       N  ...         2.0                  1
9    845010       N  ...         6.0                 20
10   845636       N  ...         2.0                  0
11   846100       N  ...         1.4                  0
12   846381       N  ...         1.0                  0
13   847990       R  ...         6.0                  6
14   848406       N  ...         1.1                  0
15   848620       R  ...         3.0                  1
16  8511133       N  ...         1.3                  0
17   851509       R  ...         4.0                  1
18   852552       N  ...         3.0                  0
19   852631       N  ...         4.4                  1
20   852763       N  ...         2.5                  0
21   852781       N  ...         3.4                 13
22   852973       N  ...         2.0                  0
23   853201       N  ...         4.0                  0
24   853612       N  ...         3.0                  2
25   853826       N  ...         1.3                  1
26   854002       N  ...         3.5                  0
27   854039       N  ...         2.5                  0
28   854253       N  ...         1.5                  0
29   854268       N  ...         3.0                 13

[30 rows x 35 columns]

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#data preprocessing
dfc['Outcome']=dfc['Outcome'].apply(lambda x:0 if (x == 'N') else 1)
dfc=dfc.set_index('ID')

In [126]:
print(dfc.groupby('Outcome').size())
dfc.head()
dfc.describe()
dfc.shape



Outcome
0    151
1     47
dtype: int64


(198, 34)

In [0]:
y=dfc['Outcome'].values
X=dfc.drop('Outcome',axis=1).values




In [128]:
X


array([[3.100e+01, 1.802e+01, 2.760e+01, ..., 8.113e-02, 5.000e+00,
        5.000e+00],
       [6.100e+01, 1.799e+01, 1.038e+01, ..., 1.189e-01, 3.000e+00,
        2.000e+00],
       [1.160e+02, 2.137e+01, 1.744e+01, ..., 9.067e-02, 2.500e+00,
        0.000e+00],
       ...,
       [1.200e+01, 1.717e+01, 2.919e+01, ..., 6.033e-02, 3.700e+00,
        0.000e+00],
       [3.000e+00, 2.142e+01, 2.284e+01, ..., 8.981e-02, 3.000e+00,
        0.000e+00],
       [6.000e+00, 1.670e+01, 2.813e+01, ..., 8.036e-02, 3.500e+00,
        0.000e+00]])

In [129]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train.shape


(158, 33)

In [130]:
X_test.shape

(40, 33)

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
import time
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [132]:
models=[]
models.append(('DEST',DecisionTreeClassifier()))
models.append(('SVM',SVC()))
models.append(('NB',GaussianNB()))
models.append(('KNN',KNeighborsClassifier()))

numfolds=3
results=[]
names=[]
for name,modelP in models:
  kfold=KFold(n_splits=numfolds)
  start=time.time()
  cv_results = cross_val_score(modelP,X_train,y_train,cv=kfold)
  end=time.time()
  results.append(cv_results)
  names.append(name)
  print("%s: %f (%f) (time taken:%f)"%(name,cv_results.mean(),cv_results.std(),end-start))



DEST: 0.658805 (0.094680) (time taken:0.012315)
SVM: 0.753628 (0.060294) (time taken:0.007329)
NB: 0.639695 (0.050801) (time taken:0.003902)
KNN: 0.683478 (0.054419) (time taken:0.009669)


In [133]:
scaler = StandardScaler().fit(X_train)
rescaledX = scaler.transform(X_train)
c_values = [0.1, 0.3, 0.5, 0.7, 0.9, 1.0, 1.3, 1.5, 1.7, 2.0]
kernel_values = ['linear', 'poly', 'rbf', 'sigmoid']
param_grid = dict(C=c_values, kernel=kernel_values)
model = SVC()
kfold = KFold(n_splits=numfolds, random_state=21)
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=kfold)
grid_result = grid.fit(rescaledX, y_train)
print("Best: %s using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


Best: 0.823052733430092 using {'C': 1.0, 'kernel': 'linear'}
0.760039 (0.062811) with: {'C': 0.1, 'kernel': 'linear'}
0.760039 (0.068244) with: {'C': 0.1, 'kernel': 'poly'}
0.753628 (0.060294) with: {'C': 0.1, 'kernel': 'rbf'}
0.753628 (0.060294) with: {'C': 0.1, 'kernel': 'sigmoid'}
0.785075 (0.030577) with: {'C': 0.3, 'kernel': 'linear'}
0.760039 (0.068244) with: {'C': 0.3, 'kernel': 'poly'}
0.753628 (0.060294) with: {'C': 0.3, 'kernel': 'rbf'}
0.753628 (0.060294) with: {'C': 0.3, 'kernel': 'sigmoid'}
0.778786 (0.037362) with: {'C': 0.5, 'kernel': 'linear'}
0.766328 (0.060992) with: {'C': 0.5, 'kernel': 'poly'}
0.753628 (0.060294) with: {'C': 0.5, 'kernel': 'rbf'}
0.747218 (0.052706) with: {'C': 0.5, 'kernel': 'sigmoid'}
0.785075 (0.037545) with: {'C': 0.7, 'kernel': 'linear'}
0.759918 (0.052715) with: {'C': 0.7, 'kernel': 'poly'}
0.753628 (0.060294) with: {'C': 0.7, 'kernel': 'rbf'}
0.740929 (0.052561) with: {'C': 0.7, 'kernel': 'sigmoid'}
0.816642 (0.031136) with: {'C': 0.9, 'kerne

In [0]:
scaler = StandardScaler().fit(X_train)
rescaledX = scaler.transform(X_train)

In [73]:
X_test

array([[29.     , 21.93   , 30.64   , ...,  0.07353,  3.5    ,  0.     ],
       [48.     , 19.8    , 21.56   , ...,  0.08255,  2.6    ,  0.     ],
       [43.     , 11.8    , 16.58   , ...,  0.103  ,  1.9    ,  0.     ],
       ...,
       [63.     , 20.73   , 31.12   , ...,  0.08218,  3.     ,  2.     ],
       [62.     , 15.61   , 19.38   , ...,  0.06829,  2.     ,  0.     ],
       [62.     , 23.27   , 22.04   , ...,  0.09187,  1.     ,  3.     ]])

In [134]:

import warnings


with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
model = SVC(C=1.0, kernel='linear')
start = time.time()
model.fit(X_train, y_train)
end = time.time()
print( "Run Time: %f" % (end-start))

Run Time: 9.891205


In [135]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
model = SVC(C=2.0, kernel='rbf')
start = time.time()
model.fit(X_train_scaled, y_train)
end = time.time()
print( "Run Time: %f" % (end-start))

Run Time: 0.004949


In [148]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    X_test_scaled = scaler.transform(X_test)
predictions = model.predict(X_test_scaled)
outputMatrix=np.column_stack((X_test,predictions))
outputMatrix

array([[40.  , 18.31, 20.58, ...,  1.2 ,  1.  ,  0.  ],
       [72.  , 14.45, 20.22, ...,  1.5 ,  0.  ,  0.  ],
       [81.  , 15.28, 22.41, ...,  1.6 ,  0.  ,  0.  ],
       ...,
       [63.  , 20.73, 31.12, ...,  3.  ,  2.  ,  0.  ],
       [11.  , 20.59, 21.24, ...,  5.5 , 20.  ,  1.  ],
       [36.  , 14.54, 27.54, ...,  6.  ,  6.  ,  0.  ]])

In [137]:
print("Accuracy score %f" % accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

Accuracy score 0.875000
              precision    recall  f1-score   support

           0       0.89      0.97      0.93        32
           1       0.80      0.50      0.62         8

    accuracy                           0.88        40
   macro avg       0.84      0.73      0.77        40
weighted avg       0.87      0.88      0.86        40



In [138]:
print(confusion_matrix(y_test, predictions))

[[31  1]
 [ 4  4]]
